export AWS_ACCESS_KEY_ID=<<>>
export AWS_SECRET_ACCESS_KEY=<<>>
export AWS_DEFAULT_REGION=<<>>

export STAGE=<<>>
export ROWANTREE_TLD=<<>>

export ACCESS_TOKEN_SECRET_KEY=<<>>
export ACCESS_TOKEN_ALGORITHM=<<>>
export ACCESS_TOKEN_EXPIRATION_TIME=30
export ACCESS_AUTH_ENDPOINT_TIMEOUT=5
export ACCESS_AUTH_ENDPOINT_RETRY_COUNT=5
export ACCESS_AUTH_ENDPOINT_SLEEP_TIME=1

export DATABASE_SERVER=<<>>
export DATABASE_NAME=<<>>
export DATABASE_USERNAME=<<>>
export DATABASE_PASSWORD=<<>>

export DOCKER_PUBLISH_API_KEY=<<>>
export DOCKER_PUBLISHER_USER=<<>>
